resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GH
      path: NeuraLegion/jfrog-example

pipelines:
  - name: nexploit
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: install_nexploit
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - cd ~
            - curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
            - sudo bash nodesource_setup.sh
            - sudo apt install nodejs
            - nodejs -v
            - npm -v
            - sudo npm install -g @neuralegion/nexploit-cli
            - nexploit-cli -v
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - add_run_variables current_runid=$run_id
            - echo Previous run ID is $prev_runid
            - echo Current run ID is $current_runid
            - echo $res_myAppRepo_resourcePath
            - echo $res_myAppRepo_gitProvider_name
            - echo $res_myAppRepo_commitSha
 
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: install_nexploit
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
 
      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: install_nexploit
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
 
      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - add_pipeline_variables prev_runid=$run_id           
            - echo $current_runid Completed
