resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GH
      path: NeuraLegion/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: Nexploit
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - cd ~
            - curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
            - sudo bash nodesource_setup.sh
            - sudo apt install nodejs
            - nodejs -v
            - npm -v
            - sudo npm install -g @neuralegion/nexploit-cli
            - nexploit-cli -v
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - add_run_variables current_runid=$run_id
            - echo Previous run ID is $prev_runid
            - echo Current run ID is $current_runid
            - echo $res_myAppRepo_resourcePath
            - echo $res_myAppRepo_gitProvider_name
            - echo $res_myAppRepo_commitSha
            - |
                SCAN_ID=$(nexploit-cli scan:run                                               \
                  --test csrf dom_xss header_security secret_tokens                           \
                  --name "🥤 Juice-Shop for a #${res_myAppRepo_commitSha} #${current_runid}"  \
                  --crawler https://juice-shop.herokuapp.com                                  \
                  --token $int_Nexploit_NEXPLOIT_TOKEN)
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 10m                         \
                --token $int_Nexploit_NEXPLOIT_TOKEN  \
                --breakpoint high_issue $SCAN_ID
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
