resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: GH
      path: NeuraLegion/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: Nexploit
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - cd ~
            - sudo apt update
            - sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
            - sudo apt install nodejs npm
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - |
                SCAN_ID=$(nexploit-cli scan:run                                               \
                  --test csrf dom_xss header_security secret_tokens                           \
                  --name "🥤 Juice-Shop for a #${res_myAppRepo_commitSha} #${current_runid}"  \
                  --crawler https://juice-shop.herokuapp.com                                  \
                  --token $int_Nexploit_NEXPLOIT_TOKEN)
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 10m                         \
                --token $int_Nexploit_NEXPLOIT_TOKEN  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
